  ...
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: prometheus
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kube-prometheus-stack-1681-prometheus
        ...
    spec:
      nodeSelector:
        telemetry: prometheus
      automountServiceAccountToken: true
      containers:
      ...
