apiVersion: v1
kind: Pod
metadata:
  name: hostaliases-pod
  spec:
    restartPolicy: Never
    hostAliases:
    - ip: "192.168.1.101"
      hostnames:
      - "apiserver"
      - "apiserver.z-k8s.svc.cloud-atlas.io"
    - ip: "192.168.1.102"
      hostnames:
      - "repo"
      - "repo.z-k8s.svc.cloud-atlas.io"
  containers:
  - name: cat-hosts
    image: busybox:1.28
    command:
    - cat
    args:
    - "/etc/hosts" 
