apiVersion: v1
kind: PersistentVolume
metadata:
  name: stable-diffusion-local-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/containerd/models"
