---
apiVersion: v1
kind: Service
metadata:
  name: fedora-dev-service
  labels:
    app: fedora-dev-tini-simple
spec:
  #type: LoadBalancer
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
  selector:
    app: fedora-dev-tini-simple
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedora-dev-tini-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedora-dev-tini-simple
  template:
    metadata:
      labels:
        app: fedora-dev-tini-simple
    spec:
      containers:
      - name: fedora-dev-tini-simple
        image: localhost:5001/fedora-dev-tini:latest
        ports:
        - containerPort: 22
        args:
        - /bin/sh
        - -c
        - /usr/sbin/sshd; sleep 10; echo 'Hello from fedora-dev-tini'; date; while
                true; do (sleep 120; echo 'Hello from fedora-dev-tini'; date); done
