---
apiVersion: v1
kind: Service
metadata:
  name: fedora-dev-service
  labels:
    app: fedora-dev-tini-1port-live
spec:
  #type: LoadBalancer
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
  selector:
    app: fedora-dev-tini-1port-live
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedora-dev-tini-1port-live
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedora-dev-tini-1port-live
  template:
    metadata:
      labels:
        app: fedora-dev-tini-1port-live
    spec:
      containers:
      - name: fedora-dev-tini-1port-live
        image: localhost:5001/fedora-dev-tini:latest
        ports:
          - containerPort: 22
            name: ssh
            protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 15
          periodSeconds: 20
