---
apiVersion: v1
kind: Service
metadata:
  name: fedora-dev-service
  labels:
    app: fedora-dev-tini-1port
spec:
  #type: LoadBalancer
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
  selector:
    app: fedora-dev-tini-1port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedora-dev-tini-1port
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedora-dev-tini-1port
  template:
    metadata:
      labels:
        app: fedora-dev-tini-1port
    spec:
      containers:
      - name: fedora-dev-tini-1port
        image: localhost:5001/fedora-dev-tini:latest
        ports:
          - containerPort: 22
            name: ssh
            protocol: TCP
