additionalPrometheusRulesMap:
  rule-name:
    groups:
    - name: disk_alert
      rules:
      - alert: DiskUsage
        expr: (node_filesystem_size_bytes{mountpoint="/"}) - (node_filesystem_free_bytes{mountpoint="/"}) >= (node_filesystem_size_bytes{mountpoint="/"}) * 0.8
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Disk usage is too high (instance {{ $labels.instance }})"
          description: "Disk usage is too high (instance {{ $labels.instance }})."
