apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: dcgm-exporter-1680364448
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-04-01T15:54:13Z"
  labels:
    app.kubernetes.io/component: dcgm-exporter
    app.kubernetes.io/instance: dcgm-exporter-1680364448
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/version: 2.6.10
    helm.sh/chart: dcgm-exporter-2.6.10
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
...
    manager: helm
    operation: Update
    time: "2023-04-01T15:54:13Z"
  name: dcgm-exporter-1680364448
  namespace: default
  resourceVersion: "6314410"
  selfLink: /api/v1/namespaces/default/services/dcgm-exporter-1680364448
  uid: fef9c429-4c9f-418b-ae62-c8012efc577b
spec:
  clusterIP: 10.233.18.35
  ports:
  - name: metrics
    port: 9400
    protocol: TCP
    targetPort: 9400
  selector:
    app.kubernetes.io/instance: dcgm-exporter-1680364448
    app.kubernetes.io/name: dcgm-exporter
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
