...
        volumeMounts:
...
        - mountPath: /prometheus
          name: kube-prometheus-stack-pv-storage
...
      volumes:
        - name: kube-prometheus-stack-pv-storage
          persistentVolumeClaim:
            claimName: kube-prometheus-stack-pvc
