...
        volumeMounts:
...
        - mountPath: /prometheus
          name: prometheus-kube-prometheus-stack-1681-prometheus-db
...
      volumes:
      - emptyDir: {}
        name: prometheus-kube-prometheus-stack-1681-prometheus-db
