apiVersion: monitoring.sigma.alipay.com/v1
kind: MonitoringRule
metadata:
  ...
spec:
  interval: 1m
  ...
    - name: alert:TooManyPodPendingC2
      expr: sum by (cluster)(cluster:unhealthy_pod_namespace_count:sum1m{phase=~"Pending|unScheduledPending|scheduledFailedPending",namespace='c2-msearcherbs'}) > 2
      for: 1m
      annotations:
        expr: 'sum by (cluster)(cluster:unhealthy_pod_namespace_count:sum1m{phase=~"Pending|unScheduledPending|scheduledFailedPending",namespace='c2-msearcherbs'}) > 2'
        value: '{{$value}}'
        severity: 'p1'
        ...
