...
spec:
  ...
  template:
    ...
    spec:
      containers:
      - args:
        - --port=8080
        - --resources=certificatesigningrequests,configmaps,cronjobs...
        - --metric-labels-allowlist=nodes=[infra.cloud-atlas/node-ip,machine.cloud-atlas.io/biz-name,k8s.cloud-atlas.io/arch],pods=[sync.k8s.cloud-atlas.io/resource-type,custom.cloud-atlas.io/runtime-class]
        image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.8.2
        imagePullPolicy: IfNotPresent
        ...
