    additionalScrapeConfigs:
    - job_name: 'store-metrics-9999'
      scrape_interval: 30s
      metrics_path: /metrics/prometheus
      static_configs:
      - targets:
        - "192.168.1.8:9999"
        - "192.168.1.7:9999"
        - "192.168.1.6:9999"
        labels:
          group: 'store-master-1'
      - targets:
        - "192.168.1.200:9999"
        - "192.168.1.197:9999"
        - "192.168.1.201:9999"
        labels:
          group: 'store-master-2'
      ...
    - job_name: 'store-metrics-10000'
      scrape_interval: 30s
      metrics_path: /metrics/prometheus
      static_configs:
      - targets:
        - "192.168.44.250:10000"
        - "192.168.44.253:10000"
        - "192.168.44.248:10000"
        - "192.168.1.3:10000"
        - "192.168.1.0:10000"
        labels:
          group: 'store-worker-1'
      - targets:
        - "192.168.1.236:10000"
        - "192.168.2.12:10000"
        - "192.168.1.251:10000"
        - "192.168.1.237:10000"
        - "192.168.1.255:10000"
        labels:
          group: 'store-worker-2'
      ...
    - job_name: 'store-metrics-10001'
      scrape_interval: 30s
      metrics_path: /metrics/prometheus
      static_configs:
      - targets:
        - "192.168.2.4:10001"
        - "192.168.2.5:10001"
        - "192.168.1.254:10001"
        - "192.168.1.253:10001"
        - "192.168.1.248:10001"
        labels:
          group: 'store-worker-1'
      - targets:
        - "192.168.1.236:10001"
        - "192.168.2.12:10001"
        - "192.168.1.251:10001"
        - "192.168.1.237:10001"
        - "192.168.1.255:10001"
        labels:
          group: 'store-worker-2'
      ...
