apiVersion: v1
kind: Pod
metadata:
  name: test-pod-5
  namespace: default
spec:
  containers:
  - name: centos
    image: centos
    command: ['sh', '-c', 'sleep 999']
    securityContext:
       privileged: false
       allowPrivilegeEscalation: false
       runAsUser: 1000
       capabilities:
          drop:
            - ALL
          add:
             - SYS_NICE
