apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dev-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.22.255.200-172.22.255.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: dev-ip-pool
  namespace: metallb-system
spec:
  ipAddressPools:
  - dev-ip-pool
