---
apiVersion: v1
kind: Service
metadata:
  name: gluster-cluster
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: gluster-cluster
subsets:
  - addresses:
      - ip: 192.168.6.15
    ports:
      - port: 1
  - addresses:
      - ip: 192.168.6.16
    ports:
      - port: 1
