apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-verify
  namespace: kube-verify
  labels:
    app: kube-verify
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-verify
  template:
    metadata:
      labels:
        app: kube-verify
    spec:
      containers:
      - name: nginx
        image: quay.io/clcollins/kube-verify:01
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: dbdata
          mountPath: /var/dbdata
          readOnly: false
      securityContext:
        runAsUser: 592
        supplementalGroups: [590]
      volumes:
      - name: dbdata
        persistentVolumeClaim:
          claimName: gluster-claim
