---
apiVersion: v1
kind: Service
metadata:
  name: fedora-dev-service
  labels:
    app: fedora-dev
spec:
  #type: LoadBalancer
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: fedora-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedora-dev-origin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedora-dev
  template:
    metadata:
      labels:
        app: fedora-dev
    spec:
      containers:
      - name: fedora-dev
        image: localhost:5001/fedora-dev:latest
        ports:
          - containerPort: 22
            name: ssh
            protocol: TCP
