...
    spec:
      containers:
      - name: fedora-dev
        image: localhost:5001/fedora-dev:latest
        env:
          - name: container
            value: "docker"
        ports:
          - containerPort: 22
            name: ssh
            protocol: TCP
