network:
  version: 2
  renderer: networkd

  ethernets:
#   eno1:
#     addresses:
#     - 192.168.6.200/24
#     gateway4: 192.168.6.11
#     nameservers:
#       addresses:
#       - 192.168.6.11
#       search: []
    eno1:
      dhcp4: false
      dhcp6: false

  bridges:
    br0:
      dhcp4: no
      dhcp6: no
      interfaces: [eno1]
      addresses: [192.168.6.200/24, 192.168.7.200/24]
      parameters:
        stp: false
        forward-delay: 4
