spec:
  ...
  selector:
    matchLabels:
      ...
  template:
    metadata:
      ...
      labels:
        ...
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: custom.k8s.cloud-atlas.io/gpu-mode
                operator: In
                values:
                - phy
      containers:
      ...
