apiVersion: v1
data:
  promYaml: |-
    scrape_configs:
    - job_name: my-job
      ...
kind: ConfigMap
metadata:
  labels:
    target: arms
    type: prometheus-yaml
  name: arms-prom-prometheus-yaml
  namespace: arms-prom
